name: Mi flujo de trabajo

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Usa Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Instala dependencias
      run: npm install

    - name: Consruir el proyecto
      run: npm run build

    - name: Ejecuta pruebas
      run: npm test
